<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
    <RootNamespace>RimExtractorCore</RootNamespace>
    
    <!-- Build Configurations -->
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="ExcelDataReader" Version="3.9.0" />
    <PackageReference Include="ICSharpCode.Decompiler" Version="10.1.1.8388" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
  </ItemGroup>

  <!-- Procedures 폴더 하위의 모든 .cs 파일을 컴파일 대상에서 제외 후 빌드 경로에 그대로 복사 -->
  <ItemGroup>
    <Compile Remove="Procedures\*\**\*.cs" />
    <None Include="Procedures\**\*.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
