<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Program Metadata -->
    <VersionPrefix>1.0.0</VersionPrefix>
    <VersionSuffix>beta</VersionSuffix>
    
    <!-- Build Configurations -->
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <SignAssembly>False</SignAssembly>
    <NoWin32Manifest>true</NoWin32Manifest>
    <LangVersion>14</LangVersion>
    <UseWindowsForms>false</UseWindowsForms>
    
    <AssemblyName>RimExtractor</AssemblyName>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    
    <!-- Avlonia -->
    <UseAvalonia>true</UseAvalonia>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationHighDpiMod>SystemAware</ApplicationHighDpiMod>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RimExtractorCore\RimExtractorCore.csproj">
      <Private>True</Private>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\InitialPathSelectWindow.axaml.cs">
      <DependentUpon>InitialPathSelectWindow.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
  
</Project>